services:
  airflow_sim:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    image: airflow_sim
    ports:
      - "8080:8080"
    volumes:
      - ../.env:/opt/airflow/.env
    environment:
      - AIRFLOW_UID=${AIRFLOW_UID}
      - AIRFLOW_CONN_SLACK_CONNECTION={"conn_type":"slackwebhook","host":"https://hooks.slack.com/services/","password":"${AIRFLOW_WEBHOOK_TOKEN}"}